// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: identity.sql

package db

import (
	"context"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    nic,
    name,
    address
) VALUES (
    $1,
    $2,
    $3)
RETURNING nic, name, address
`

type CreatePersonParams struct {
	Nic     string `json:"nic"`
	Name    string `json:"name"`
	Address string `json:"address"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Nic, arg.Name, arg.Address)
	var i Person
	err := row.Scan(&i.Nic, &i.Name, &i.Address)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT nic, name, address FROM persons
WHERE nic = $1
`

func (q *Queries) GetPerson(ctx context.Context, nic string) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, nic)
	var i Person
	err := row.Scan(&i.Nic, &i.Name, &i.Address)
	return i, err
}
